version: '2'

services:
  gogs-db:
    image: mariadb
    container_name: gogs-db
    expose:
      - "3306"
    volumes:
      - gogs-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ASECUREPASSWORD
      MYSQL_DATABASE: gogs
  
  gogs:
    image: gogs/gogs
    container_name: gogs
    expose:
      - "22"
      - "443"
      - "3000"
    volumes:
      - gogs-data:/data:rw
    environment:
      VIRTUAL_HOST: yourdomainhere.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: yourdomainhere.com
      LETSENCRYPT_EMAIL: you@some-email-host.com

volumes:
  gogs-db:
  gogs-data:

networks:
  default:
    external:
      name: nginx-proxy
